In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv("Laptop_Sales.csv")

In [ ]:
df.shape

(480, 10)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 480 entries, 0 to 479
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  480 non-null    int64
 1   Brands      480 non-null    object
 2   Models      480 non-null    object
 3   Prices      480 non-null    object
 4   Processors  480 non-null    object
 5   RAM         438 non-null    float64
 6   ROM         438 non-null    float64
 7   OS          480 non-null    object
 8   Display     480 non-null    float64
 9   Warranty    480 non-null    int64
dtypes: float64(3), int64(2), object(5)
memory usage: 37.6+ KB

In [ ]:
df

,Unnamed: 0,Brands,Models,Prices,Processors,RAM,ROM,OS,Display,Warranty
0,0,Infinix,Y4,"₹34,990",Intel Core i5,16.0,512.0,Windows 11,16.0,1
1,1,MSI,Thin,"₹51,990",Intel Core i5,16.0,512.0,Windows 11,15.6,2
2,2,Acer,Aspire,"₹15,980",Intel Celeron Dual Core Processor,8.0,128.0,Windows 11,11.6,1
3,3,ASUS,Vivobook,"₹41,990",AMD Ryzen 3,8.0,512.0,Windows 11,15.6,1
4,4,Lenovo,IdeaPad,"₹39,990",Unknown,16.0,512.0,Windows 11,15.6,1
...,...,...,...,...,...,...,...,...,...,...
475,475,DELL,Intel,"₹59,740",Intel Core i5,8.0,1.0,Windows 11,14.0,1
476,476,ASUS,Vivobook,"₹40,990",Intel Core i7,8.0,512.0,Windows 11,14.0,1
477,477,HP,Intel,"₹51,490",Intel Core i7,16.0,512.0,Windows 11,15.6,1
478,478,DELL,Inspiron,"₹49,790",Intel Core i3,16.0,512.0,Windows 11,15.6,1
479,479,HP,15s,"₹33,990",Unknown,8.0,512.0,Windows 11,15.6,1

In [ ]:
df.drop("Unnamed: 0", axis = 1, inplace = True)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 480 entries, 0 to 479
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Brands      480 non-null    object
 1   Models      480 non-null    object
 2   Prices      480 non-null    object
 3   Processors  480 non-null    object
 4   RAM         438 non-null    float64
 5   ROM         438 non-null    float64
 6   OS          480 non-null    object
 7   Display     480 non-null    float64
 8   Warranty    480 non-null    int64
dtypes: float64(3), int64(1), object(5)
memory usage: 33.9+ KB

In [ ]:
df

,Brands,Models,Prices,Processors,RAM,ROM,OS,Display,Warranty
0,Infinix,Y4,"₹34,990",Intel Core i5,16.0,512.0,Windows 11,16.0,1
1,MSI,Thin,"₹51,990",Intel Core i5,16.0,512.0,Windows 11,15.6,2
2,Acer,Aspire,"₹15,980",Intel Celeron Dual Core Processor,8.0,128.0,Windows 11,11.6,1
3,ASUS,Vivobook,"₹41,990",AMD Ryzen 3,8.0,512.0,Windows 11,15.6,1
4,Lenovo,IdeaPad,"₹39,990",Unknown,16.0,512.0,Windows 11,15.6,1
...,...,...,...,...,...,...,...,...,...
475,DELL,Intel,"₹59,740",Intel Core i5,8.0,1.0,Windows 11,14.0,1
476,ASUS,Vivobook,"₹40,990",Intel Core i7,8.0,512.0,Windows 11,14.0,1
477,HP,Intel,"₹51,490",Intel Core i7,16.0,512.0,Windows 11,15.6,1
478,DELL,Inspiron,"₹49,790",Intel Core i3,16.0,512.0,Windows 11,15.6,1
479,HP,15s,"₹33,990",Unknown,8.0,512.0,Windows 11,15.6,1

In [ ]:
df["Brands"].value_counts() # this column is ok

Brands
ASUS         123
Lenovo       110
Acer          72
HP            72
SAMSUNG       37
DELL          21
MSI           19
Infinix        9
MOTOROLA       5
Apple          4
CHUWI          3
Primebook      2
GIGABYTE       1
Ultimus        1
Thomson        1
Name: count, dtype: int64

In [ ]:
df["Models"].value_counts() # this column is ok

Models
Vivobook    102
IdeaPad      68
Aspire       43
Galaxy       37
Intel        35
           ...
Zenbook       1
14s           1
MSO'2021      1
Gaming        1
X3            1
Name: count, Length: 61, dtype: int64

In [ ]:
df["Prices"] # this column is ok

0      ₹34,990
1      ₹51,990
2      ₹15,980
3      ₹41,990
4      ₹39,990
        ...
475    ₹59,740
476    ₹40,990
477    ₹51,490
478    ₹49,790
479    ₹33,990
Name: Prices, Length: 480, dtype: object

In [ ]:
df["Display"].value_counts() # this column is ok

Display
15.6    290
14.0    113
16.0     35
14.5     19
11.6      8
14.1      5
13.3      2
16.1      2
13.6      2
15.5      2
13.0      1
15.3      1
Name: count, dtype: int64

In [ ]:
df["Warranty"].value_counts() # this column is ok

Warranty
1    469
2     11
Name: count, dtype: int64

In [ ]:
df["OS"].value_counts()

OS
Windows 11    461
Chrome         11
Unknown         7
Windows 10      1
Name: count, dtype: int64

In [ ]:
df[df["OS"] == "Unknown"]

,Brands,Models,Prices,Processors,RAM,ROM,OS,Display,Warranty
139,Apple,2020,"₹66,990",Unknown,8.0,256.0,Unknown,13.3,1
153,Apple,MacBook,"₹1,25,990",Unknown,16.0,512.0,Unknown,13.0,1
164,HP,250,"₹23,390",Unknown,8.0,256.0,Unknown,15.6,1
215,Apple,Apple,"₹1,44,990",Intel Core i5,24.0,512.0,Unknown,16.0,1
289,Primebook,4G,"₹15,490",MediaTek MT8788,4.0,64.0,Unknown,14.0,1
408,Primebook,Wifi,"₹14,490",MediaTek MT8183,4.0,128.0,Unknown,15.6,1
459,Apple,MacBook,"₹1,11,990",Unknown,16.0,256.0,Unknown,15.6,1

In [ ]:
df.loc[(df["Brands"] == "Apple") & (df["OS"].isin(["Unknown"])), "OS"] = "Mac OS"

In [ ]:
df.loc[(df["Brands"] == "Primebook") & (df["OS"].isin(["Unknown"])), "OS"] = "Android OS"

In [ ]:
df.loc[(df["Brands"] == "HP") & (df["OS"].isin(["Unknown"])), "OS"] = "DOS OS"

In [ ]:
df["OS"].value_counts() # this column is ok

OS
Windows 11    461
Chrome         11
Mac OS          4
Android OS      2
DOS OS          1
Windows 10      1
Name: count, dtype: int64

In [ ]:
df["Processors"].value_counts()

Processors
Unknown                              164
Intel Core i5                        129
Intel Core i3                         50
AMD Ryzen 5                           34
Intel Core i7                         24
AMD Ryzen 3                           18
Intel Celeron Dual Core Processor     16
Intel Core Ultra                      12
AMD Ryzen 7                           10
Intel Core 5                           6
Intel Core i9                          4
MediaTek Kompanio 520                  3
Intel Core 7                           2
Intel Celeron Quad Core Processor      2
MediaTek MediaTek Kompanio 528         1
Apple M1 Pro                           1
Apple M3 Pro                           1
MediaTek MT8788                        1
MediaTek MT8183                        1
Apple M2 Pro                           1
Name: count, dtype: int64

In [ ]:
df['Processors'] = df['Processors'].replace('unknown', np.nan)
# df['Processors'].fillna(method='ffill', inplace=True)

In [ ]:
df[df["Processors"] == "Unknown"]

,Brands,Models,Prices,Processors,RAM,ROM,OS,Display,Warranty
4,Lenovo,IdeaPad,"₹39,990",Unknown,16.0,512.0,Windows 11,15.6,1
10,DELL,15,"₹41,990",Unknown,16.0,512.0,Windows 11,15.6,1
16,Lenovo,100e,"₹9,999",Unknown,4.0,32.0,Chrome,11.6,1
22,MSI,Modern,"₹42,999",Unknown,8.0,512.0,Windows 11,14.0,1
27,Acer,Swift,"₹59,990",Unknown,16.0,512.0,Windows 11,14.5,1
...,...,...,...,...,...,...,...,...,...
469,DELL,15,"₹69,490",Unknown,16.0,512.0,Windows 11,15.3,1
470,ASUS,Vivobook,"₹94,990",Unknown,16.0,1.0,Windows 11,15.6,1
473,HP,15s,"₹73,990",Unknown,16.0,512.0,Windows 11,14.0,1
474,Acer,Aspire,"₹30,990",Unknown,8.0,512.0,Windows 11,15.6,1
479,HP,15s,"₹33,990",Unknown,8.0,512.0,Windows 11,15.6,1

In [ ]:
df["Processors"].value_counts()

Processors
Unknown                              164
Intel Core i5                        129
Intel Core i3                         50
AMD Ryzen 5                           34
Intel Core i7                         24
AMD Ryzen 3                           18
Intel Celeron Dual Core Processor     16
Intel Core Ultra                      12
AMD Ryzen 7                           10
Intel Core 5                           6
Intel Core i9                          4
MediaTek Kompanio 520                  3
Intel Core 7                           2
Intel Celeron Quad Core Processor      2
MediaTek MediaTek Kompanio 528         1
Apple M1 Pro                           1
Apple M3 Pro                           1
MediaTek MT8788                        1
MediaTek MT8183                        1
Apple M2 Pro                           1
Name: count, dtype: int64

In [ ]:
df['Processors'] = df['Processors'].replace('Unknown', np.nan)
df['Processors'] = df['Processors'].fillna(method='ffill')

<ipython-input-33-a29629530ff9>:2: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['Processors'] = df['Processors'].fillna(method='ffill')

In [ ]:
df["Processors"].value_counts() # this column is ok

Processors
Intel Core i5                        212
Intel Core i3                         76
AMD Ryzen 5                           49
Intel Core i7                         31
AMD Ryzen 3                           27
Intel Celeron Dual Core Processor     20
AMD Ryzen 7                           16
Intel Core Ultra                      16
Intel Core 5                           8
Intel Core i9                          7
MediaTek Kompanio 520                  5
Intel Core 7                           3
Intel Celeron Quad Core Processor      3
Apple M3 Pro                           2
MediaTek MediaTek Kompanio 528         1
Apple M1 Pro                           1
MediaTek MT8788                        1
MediaTek MT8183                        1
Apple M2 Pro                           1
Name: count, dtype: int64

In [ ]:
df["RAM"].value_counts()

RAM
16.0    243
8.0     172
4.0      11
24.0      6
12.0      5
32.0      1
Name: count, dtype: int64

In [ ]:
df["RAM"].isnull().sum()

np.int64(42)

In [ ]:
df['RAM'] = df['RAM'].fillna(df["RAM"].isnull())

In [ ]:
df["RAM"].value_counts()

RAM
16.0    243
8.0     172
True     42
4.0      11
24.0      6
12.0      5
32.0      1
Name: count, dtype: int64

In [ ]:
df['RAM'] = df['RAM'].replace(True, np.nan)
df['RAM'] = df['RAM'].fillna(method='ffill')

<ipython-input-48-a2ba8863bde7>:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['RAM'] = df['RAM'].replace(True, np.nan)
<ipython-input-48-a2ba8863bde7>:2: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['RAM'] = df['RAM'].fillna(method='ffill')

In [ ]:
df["RAM"].value_counts() # this column is ok

RAM
16.0    267
8.0     189
4.0      12
24.0      6
12.0      5
32.0      1
Name: count, dtype: int64

In [ ]:
df["ROM"].value_counts()

ROM
512.0    335
1.0       72
256.0     17
128.0      7
64.0       6
32.0       1
Name: count, dtype: int64

In [ ]:
df["ROM"].isnull().sum()

np.int64(0)

In [ ]:
df["ROM"] = df["ROM"].fillna(df['ROM'].isnull())

In [ ]:
df["ROM"].value_counts()

ROM
512.0    335
1.0      114
256.0     17
128.0      7
64.0       6
32.0       1
Name: count, dtype: int64

In [ ]:
df["ROM"] = df["ROM"].replace(1,1024)

<ipython-input-56-f37f0669c161>:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df["ROM"] = df["ROM"].replace(1,1024)

In [ ]:
df["ROM"].value_counts() # it is ok

ROM
512.0     335
1024.0    114
256.0      17
128.0       7
64.0        6
32.0        1
Name: count, dtype: int64

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 480 entries, 0 to 479
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Brands      480 non-null    object
 1   Models      480 non-null    object
 2   Prices      480 non-null    object
 3   Processors  480 non-null    object
 4   RAM         480 non-null    float64
 5   ROM         480 non-null    float64
 6   OS          480 non-null    object
 7   Display     480 non-null    float64
 8   Warranty    480 non-null    int64
dtypes: float64(3), int64(1), object(5)
memory usage: 33.9+ KB

In [ ]:
df

,Brands,Models,Prices,Processors,RAM,ROM,OS,Display,Warranty
0,Infinix,Y4,"₹34,990",Intel Core i5,16.0,512.0,Windows 11,16.0,1
1,MSI,Thin,"₹51,990",Intel Core i5,16.0,512.0,Windows 11,15.6,2
2,Acer,Aspire,"₹15,980",Intel Celeron Dual Core Processor,8.0,128.0,Windows 11,11.6,1
3,ASUS,Vivobook,"₹41,990",AMD Ryzen 3,8.0,512.0,Windows 11,15.6,1
4,Lenovo,IdeaPad,"₹39,990",AMD Ryzen 3,16.0,512.0,Windows 11,15.6,1
...,...,...,...,...,...,...,...,...,...
475,DELL,Intel,"₹59,740",Intel Core i5,8.0,1024.0,Windows 11,14.0,1
476,ASUS,Vivobook,"₹40,990",Intel Core i7,8.0,512.0,Windows 11,14.0,1
477,HP,Intel,"₹51,490",Intel Core i7,16.0,512.0,Windows 11,15.6,1
478,DELL,Inspiron,"₹49,790",Intel Core i3,16.0,512.0,Windows 11,15.6,1
479,HP,15s,"₹33,990",Intel Core i3,8.0,512.0,Windows 11,15.6,1

In [ ]:
df['Prices'] = df['Prices'].str.replace('₹', '', regex=False).str.replace(',', '', regex=False)

In [ ]:
df

,Brands,Models,Prices,Processors,RAM,ROM,OS,Display,Warranty
0,Infinix,Y4,34990,Intel Core i5,16.0,512.0,Windows 11,16.0,1
1,MSI,Thin,51990,Intel Core i5,16.0,512.0,Windows 11,15.6,2
2,Acer,Aspire,15980,Intel Celeron Dual Core Processor,8.0,128.0,Windows 11,11.6,1
3,ASUS,Vivobook,41990,AMD Ryzen 3,8.0,512.0,Windows 11,15.6,1
4,Lenovo,IdeaPad,39990,AMD Ryzen 3,16.0,512.0,Windows 11,15.6,1
...,...,...,...,...,...,...,...,...,...
475,DELL,Intel,59740,Intel Core i5,8.0,1024.0,Windows 11,14.0,1
476,ASUS,Vivobook,40990,Intel Core i7,8.0,512.0,Windows 11,14.0,1
477,HP,Intel,51490,Intel Core i7,16.0,512.0,Windows 11,15.6,1
478,DELL,Inspiron,49790,Intel Core i3,16.0,512.0,Windows 11,15.6,1
479,HP,15s,33990,Intel Core i3,8.0,512.0,Windows 11,15.6,1

In [ ]:
df["Prices"] = df["Prices"].astype(int)

In [ ]:
df["Prices"].dtype

dtype('int64')

In [ ]:
df["RAM"] = df["RAM"].astype(int)

In [ ]:
df["ROM"] = df["ROM"].astype(int)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 480 entries, 0 to 479
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Brands      480 non-null    object
 1   Models      480 non-null    object
 2   Prices      480 non-null    int64
 3   Processors  480 non-null    object
 4   RAM         480 non-null    int64
 5   ROM         480 non-null    int64
 6   OS          480 non-null    object
 7   Display     480 non-null    float64
 8   Warranty    480 non-null    int64
dtypes: float64(1), int64(4), object(4)
memory usage: 33.9+ KB

In [ ]:
df

,Brands,Models,Prices,Processors,RAM,ROM,OS,Display,Warranty
0,Infinix,Y4,34990,Intel Core i5,16,512,Windows 11,16.0,1
1,MSI,Thin,51990,Intel Core i5,16,512,Windows 11,15.6,2
2,Acer,Aspire,15980,Intel Celeron Dual Core Processor,8,128,Windows 11,11.6,1
3,ASUS,Vivobook,41990,AMD Ryzen 3,8,512,Windows 11,15.6,1
4,Lenovo,IdeaPad,39990,AMD Ryzen 3,16,512,Windows 11,15.6,1
...,...,...,...,...,...,...,...,...,...
475,DELL,Intel,59740,Intel Core i5,8,1024,Windows 11,14.0,1
476,ASUS,Vivobook,40990,Intel Core i7,8,512,Windows 11,14.0,1
477,HP,Intel,51490,Intel Core i7,16,512,Windows 11,15.6,1
478,DELL,Inspiron,49790,Intel Core i3,16,512,Windows 11,15.6,1
479,HP,15s,33990,Intel Core i3,8,512,Windows 11,15.6,1

In [ ]:
df.to_csv("Filpkart_Laptop_Sales.csv", index=False)

In [ ]:
df2 = pd.read_csv("Filpkart_Laptop_Sales.csv")

In [ ]:
df2.shape

(480, 9)

In [ ]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 480 entries, 0 to 479
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Brands      480 non-null    object
 1   Models      480 non-null    object
 2   Prices      480 non-null    int64
 3   Processors  480 non-null    object
 4   RAM         480 non-null    int64
 5   ROM         480 non-null    int64
 6   OS          480 non-null    object
 7   Display     480 non-null    float64
 8   Warranty    480 non-null    int64
dtypes: float64(1), int64(4), object(4)
memory usage: 33.9+ KB

In [ ]:
df2

,Brands,Models,Prices,Processors,RAM,ROM,OS,Display,Warranty
0,Infinix,Y4,34990,Intel Core i5,16,512,Windows 11,16.0,1
1,MSI,Thin,51990,Intel Core i5,16,512,Windows 11,15.6,2
2,Acer,Aspire,15980,Intel Celeron Dual Core Processor,8,128,Windows 11,11.6,1
3,ASUS,Vivobook,41990,AMD Ryzen 3,8,512,Windows 11,15.6,1
4,Lenovo,IdeaPad,39990,AMD Ryzen 3,16,512,Windows 11,15.6,1
...,...,...,...,...,...,...,...,...,...
475,DELL,Intel,59740,Intel Core i5,8,1024,Windows 11,14.0,1
476,ASUS,Vivobook,40990,Intel Core i7,8,512,Windows 11,14.0,1
477,HP,Intel,51490,Intel Core i7,16,512,Windows 11,15.6,1
478,DELL,Inspiron,49790,Intel Core i3,16,512,Windows 11,15.6,1
479,HP,15s,33990,Intel Core i3,8,512,Windows 11,15.6,1